// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ymwrtkqisfknwxbbhhdt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inltd3J0a3Fpc2Zrbnd4YmJoaGR0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjA1MzE0MjIsImV4cCI6MjA3NjEwNzQyMn0.Xd8gyUsEjZQtdvdiBRDGMvL-3KigezbCxw40kJ42TwI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});